package SiegeCard.Util;

public enum Rolls {
    RANDOM,
    BATTERING_RAM,
    LADDER,
    SIEGE_TOWER,
    NORMAL_ATTACK_BATTERING_RAM,
    NORMAL_ATTACK_LADDER,
    NORMAL_ATTACK_SIEGETOWER,
    CIRCLE_ATTACK_BATTERING_RAM,
    CIRCLE_ATTACK_LADDER,
    CIRCLE_ATTACK_SIEGETOWER,
    BOILING_ATTACK_BATTERING_RAM,
    BOILING_ATTACK_LADDER,
    BOILING_ATTACK_SIEGETOWER,
    CLOSE_COMBAT,
    ENEMY_LINE_CHECK,
    SUPPLY_RAID_ROLL,
    SABOTAGE_ROLL,
    COUPURE_ROLL,
    RALLY_TROOPS,
    BOOST_RALLY_TROOPS

}

