package SiegeCard.Util;

public enum Rules {

    //Values used for CREATING the dice ONLY!!!
    TREBUCHET_ATTACK,

    ILLNESS,
    GUARDS_DISTRACTED,

     SUPPLIES_SPOILED,
     BAD_WEATHER,
     BOILING_OIL,

     DEATH_OF_A_LEADER,
     GATE_FORTIFIED,
     FLAMING_ARROWS,

     VOLLEY_OF_ARROWS,
     COLLAPSED,
     REPAIRED_TREBUCHET,

     COVER_OF_DARKNESS,
     ENEMY_FATIGUE,
     RALLY,

     DETERMINED_ENEMY,
     IRON_SHIELDS,
     FAITH

}
